sudo: required
sercices:
    - docker

before_install:
    - docker build -t gavinxu/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gavinxu/react-test npm test

after_success:
    - docker build -t gavinxu/multi-client ./client
    - docker build -t gavinxu/multi-nginx ./nginx
    - docker build -t gavinxu/multi-server ./server
    - docker build -t gavinxu/multi-worker ./worker        
    # login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push gavinxu838/multi-client
    - docker push gavinxu838/multi-nginx
    - docker push gavinxu838/multi-server
    - docker push gavinxu838/multi-worker